version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rtsp-server:
    image: bluenviron/mediamtx
    container_name: rtsp-server
    restart: unless-stopped
    network_mode: host

  ffmpeg-camera:
    image: jrottenberg/ffmpeg:7.0-alpine
    container_name: ffmpeg-camera
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./video.mp4:/video/video.mp4  
    command: >
      -re -stream_loop -1 -i /video/video.mp4
      -c:v libx264
      -preset ultrafast
      -tune zerolatency
      -g 25
      -rtsp_transport tcp
      -f rtsp rtsp://localhost:8554/cam0
      
  person_queue_count:
    build:
      context: ./person_queue_count  # path to directory with Dockerfile
    container_name: person_queue_count
    restart: always
    network_mode: host
    devices:
      - /dev/accel/accel0
    environment:
          - DEVICE=NPU
          - SOURCE=rtsp://localhost:8554/cam0 

